# 4 语法专题

## 4.1 数据类型的转化

### 概述

虽然变量的数据类型是不确定的，但是各种运算符对数据类型是有要求的。如果运算符发现，运算子的类型与预期不符，就会自动转换类型。

### 强制转换

主要是下面三个函数

- Number()
- String()
- Boolean()

##### Number()

```js
// 数值：转换后还是原来的值
Number(324) // 324

// 字符串：如果可以被解析为数值，则转换为相应的数值
Number('324') // 324

// 字符串：如果不可以被解析为数值，返回 NaN
Number('324abc') // NaN

// 空字符串转为0
Number('') // 0

// 布尔值：true 转成 1，false 转成 0
Number(true) // 1
Number(false) // 0

// undefined：转成 NaN
Number(undefined) // NaN

// null：转成0
Number(null) // 0
```

Number比ParseInt要严格，因为ParseInt('12ab')会转换为12

##### String()

String函数可以将任意类型的值转化成字符串。

```js
String(123) // "123"
String('abc') // "abc"
String(true) // "true"
String(undefined) // "undefined"
String(null) // "null"
```

##### Boolean()

可以将任意类型的值转为布尔值。

```js
Boolean(undefined) // false
Boolean(null) // false
Boolean(0) // false
Boolean(NaN) // false
Boolean('') // false
```

注意，所有对象（包括空对象）的转换结果都是true，包括false对应的布尔对象`new Boolean(false)`也是true

```js
Boolean({}) // true
Boolean([]) // true
Boolean(new Boolean(false)) // true
```

## 4.2 错误处理机制

### Error

- message：错误提示信息
- name：错误名称（非标准属性）
- stack：错误的堆栈（非标准属性）

JavaScript 解析或运行时，一旦发生错误，引擎就会抛出一个错误对象。JavaScript 原生提供Error构造函数，所有抛出的错误都是这个构造函数的实例。

JavaScript 语言标准只提到，Error实例对象必须有message属性，表示出错时的提示信息，没有提到其他属性。大多数 JavaScript 引擎，对Error实例还提供name和stack属性，分别表示错误的名称和错误的堆栈，但它们是非标准的，不是每种实现都有。

### Error派生的错误类型

Error是最泛化的错误类型，js在Error的基础上还有其他6种更具体的错误类型。

- SyntaxError：解析代码时发生的语法错误
- ReferenceError：引用一个不存在的变量时发生的错误。另外，将一个值赋值给无法赋值的对象，比如对函数的运行结果或者this赋值，也会引发这个错误。
- RangeError：主要有几种情况，一是数组长度为负数，二是Number对象的方法参数超出范围，以及函数堆栈超过最大值。
- TypeError：变量或参数不是预期类型时发生的错误。比如，对字符串、布尔值、数值等原始类型的值使用new命令，就会抛出这种错误，因为new命令的参数应该是一个构造函数。
- URIError：URI 相关函数的参数不正确时抛出的错误，主要涉及encodeURI()、decodeURI()、encodeURIComponent()、decodeURIComponent()、escape()和unescape()这六个函数。
- EvalError：eval函数没有被正确执行时。该错误类型已经不再使用了，只是为了保证与以前代码兼容，才继续保留。

### 自定义错误

自定义一个错误对象UserError，让它继承Error对象。然后，就可以生成这种自定义类型的错误了。

```js
function UserError(message) {
  this.message = message || '默认信息';
  this.name = 'UserError';
}

UserError.prototype = new Error();
UserError.prototype.constructor = UserError;

let customError = new UserError('这是自定义的错误！');
customError.message
// "这是自定义的错误！"
```

